on: [push]

jobs:
  jobs:
  build:
    name: Enforce advanced security scanning
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run enforcer tool
      uses: github/advanced-security-enforcer@main
      env:
        GH_ACTOR='Put your email here'
        GH_TOKEN='Put your token here'
        ORGANIZATION='Put your organization name here'
        PR_BODY='Put the text you want to appear in the pull request body'